source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml'
gem 'json'

group :cli do
  gem "thor"
  gem "systemu"
end

group :test do
  gem "rspec"
  gem "rack-test"
end
