source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml'
gem 'json'
gem 'systemu'
gem 'redcarpet'

group :cli do
  gem 'thor'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end

gem 'rack', '< 3'
gem 'webrick', '~> 1.8'
